"use strict";
const assert = require("node:assert/strict");
const { normalizeOutcomes, validUrl } = require("../src/tasktra/portal_static/portal-outcomes.js");
let checks = 0; function check(name, fn) { fn(); checks++; console.log("PASS " + name); }
const job = { job_id:"job-1", goal_id:"goal-1", title:"Verified job", state:"completed", verification:{verified:true,policy:"deterministic-direct",recorded_at:"2026-10-07T19:10:00Z",reason:"Matching evidence"}, attempt_count:2,retry_count:1,attempt_duration_ms:60000,timed_attempts:1,attempts_shown:2,attempts_partial:false,usage:{total_tokens:222,input_tokens:200,cached_input_tokens:100,output_tokens:22,measured_runs:1,unknown_runs:1,attributed_runs:2,partial:true},evidence:{workflow_sha256:"f".repeat(64),checks:[{name:"Recorded check",status:"passed",exit_code:0,elapsed_ms:50}],deliverables:[{kind:"commit",value:"a".repeat(40)},{kind:"path",value:"docs/result.md"},{kind:"link",value:"https://github.com/example/project/commit/"+"a".repeat(40)}],partial:false} };
const raw = {version:1,jobs:[job],total:1,shown:1,partial:false,summary:{completed_jobs:1,verified_jobs:1,measured_verified_jobs:1,attributable_runs:2,unattributed_runs:0,measured_tokens_for_verified_jobs:222,tokens_per_measured_verified_job:222,unknown_usage_runs:1,partial:true},by_model:[{model:"model-a",measured_runs:1,verified_jobs:1,total_tokens:222,tokens_per_measured_run:222,failed_tokens:0,cache_fraction:.5}]};
check("normalizes bounded verified outcome cohorts",()=>{const report=normalizeOutcomes(raw);assert.equal(report.available,true);assert.equal(report.jobs.length,1);assert.equal(report.jobs[0].evidence.deliverables.length,3);assert.equal(report.summary.tokens_per_measured_verified_job,222);});
check("strict envelopes reject invalid counts and partial flags",()=>{for(const value of [{...raw,total:-1},{...raw,shown:2},{...raw,partial:"false"},{...raw,total:2,partial:false},{...raw,summary:null}])assert.equal(normalizeOutcomes(value).available,false);});
check("invalid job entries become partial rather than trusted records",()=>{const bad={...job,job_id:"job-2",retry_count:3};const report=normalizeOutcomes({...raw,jobs:[job,bad],total:2,shown:2,partial:false});assert.equal(report.available,true);assert.equal(report.jobs.length,1);assert.equal(report.partial,true);assert.equal(report.invalid_jobs,1);});
check("unsafe deliverables are omitted and safe github links stay narrow",()=>{const link="https://github.com/example/project/commit/"+"a".repeat(40);assert.equal(validUrl(link),link);for(const value of ["http://github.com/example/project/commit/a","https://evil.example/x","https://github.com/example/project/commit/a?x=1","https://user@github.com/example/project/commit/a","https://github.com:444/example/project/commit/abcdef0","https://github.com/example/project/commit/not-a-sha","https://github.com/example/project/actions/other/1","https://github.com/example/project/commit/abcdef0/"])assert.equal(validUrl(value),null);const unsafe={...job,evidence:{...job.evidence,deliverables:[{kind:"link",value:"https://evil.example/x"},{kind:"path",value:"../../private"}],partial:false}};const report=normalizeOutcomes({...raw,jobs:[unsafe]});assert.equal(report.jobs[0].evidence.deliverables.length,0);assert.equal(report.jobs[0].evidence.partial,true);});
check("verified cohorts reject contradictory verification and zero-denominator averages",()=>{const noHash={...job,evidence:{...job.evidence,workflow_sha256:null}};assert.equal(normalizeOutcomes({...raw,jobs:[noHash]}).jobs.length,0);const badSummary={...raw,summary:{...raw.summary,measured_verified_jobs:0,measured_tokens_for_verified_jobs:222,tokens_per_measured_verified_job:222}};assert.equal(normalizeOutcomes(badSummary).available,false);});
check("job attribution and token arithmetic cannot contradict recorded measurements",()=>{const mismatch={...job,usage:{...job.usage,attributed_runs:3}};assert.equal(normalizeOutcomes({...raw,jobs:[mismatch]}).jobs.length,0);const tokenMismatch={...job,usage:{...job.usage,input_tokens:201}};assert.equal(normalizeOutcomes({...raw,jobs:[tokenMismatch]}).jobs.length,0);const cacheMismatch={...job,usage:{...job.usage,cached_input_tokens:203}};assert.equal(normalizeOutcomes({...raw,jobs:[cacheMismatch]}).jobs.length,0);});
check("complete cohorts reconcile jobs and prohibit duplicate or oversized models",()=>{const duplicate={...raw,summary:{...raw.summary,partial:false},jobs:[job],by_model:[raw.by_model[0],{...raw.by_model[0]}]};assert.equal(normalizeOutcomes(duplicate).available,false);const oversized={...raw,summary:{...raw.summary,partial:false},by_model:[{...raw.by_model[0],measured_runs:3,tokens_per_measured_run:74}]};assert.equal(normalizeOutcomes(oversized).available,false);});
check("null usage remains unknown instead of zero",()=>{const unknown={...job,usage:{...job.usage,total_tokens:null,input_tokens:null,cached_input_tokens:null,output_tokens:null,measured_runs:0,unknown_runs:2,attributed_runs:2}};const report=normalizeOutcomes({...raw,jobs:[unknown],by_model:[]});assert.equal(report.jobs[0].usage.total_tokens,null);assert.equal(report.jobs[0].usage.measured_runs,0);});
check("complete unmeasured and empty cohorts remain available with null metrics",()=>{const unmeasured={...job,usage:{total_tokens:null,input_tokens:null,cached_input_tokens:null,output_tokens:null,measured_runs:0,unknown_runs:0,attributed_runs:0,partial:false}};const summary={completed_jobs:1,verified_jobs:1,measured_verified_jobs:0,attributable_runs:0,unattributed_runs:0,measured_tokens_for_verified_jobs:null,tokens_per_measured_verified_job:null,unknown_usage_runs:0,partial:false};const result=normalizeOutcomes({...raw,jobs:[unmeasured],summary,by_model:[]});assert.equal(result.available,true);assert.equal(result.summary.tokens_per_measured_verified_job,null);assert.equal(normalizeOutcomes({...raw,jobs:[],total:0,shown:0,summary:{...summary,completed_jobs:0,verified_jobs:0},by_model:[]}).available,true)});
check("model averages and aggregate sample counts cannot fabricate comparisons",()=>{const badAverage=normalizeOutcomes({...raw,by_model:[{...raw.by_model[0],tokens_per_measured_run:999}]});assert.equal(badAverage.by_model.length,0);assert.equal(badAverage.partial,true);assert.equal(normalizeOutcomes({...raw,by_model:[raw.by_model[0],{...raw.by_model[0],model:"different-model"}]}).available,false)});
check("complete model buckets account for the measured cohort",()=>{const complete={...raw,summary:{...raw.summary,partial:false},jobs:[{...job,usage:{...job.usage,partial:false}}]};assert.equal(normalizeOutcomes({...complete,by_model:[]}).available,false);assert.equal(normalizeOutcomes({...complete,by_model:[{...raw.by_model[0],total_tokens:100,tokens_per_measured_run:100}]}).available,false);assert.equal(normalizeOutcomes(complete).available,true)});
console.log(`portal outcomes checks passed (${checks})`);
