"""Compile Tasktra's canonical catalog into runtime projections.

The catalog is deliberately runtime-neutral.  This module is the one place that
knows projection paths, so agent-facing instructions do not have to duplicate
runtime or policy details.
"""

from __future__ import annotations

from dataclasses import dataclass
from hashlib import sha256
import json
import os
from pathlib import Path, PurePosixPath
import re
import stat
import tempfile
import tomllib
from typing import Iterable, Mapping

from .contracts import ContractError, validate_named
from .config import ProjectRoute
from .identifiers import IdentifierError, require_identifier
from .model_policy import (
    CodexModelPolicy,
    ModelPolicyError,
    RoleModelMetadata,
)


class CatalogError(ValueError):
    """Raised when a catalog or pack selection is invalid."""


class ProjectionError(CatalogError):
    """Raised when a projection cannot be safely materialized."""


@dataclass(frozen=True)
class Document:
    identifier: str
    title: str
    family: str
    source: Path
    content: str
    model_tier: str | None = None
    reasoning_effort: str | None = None
    sandbox_mode: str | None = None


@dataclass(frozen=True)
class ProjectAgent:
    identifier: str
    description: str


@dataclass(frozen=True)
class Pack:
    identifier: str
    version: str
    dependencies: tuple[str, ...]
    conflicts: tuple[str, ...]
    roles: tuple[str, ...]
    skills: tuple[str, ...]
    contract_version: int = 1
    required_capabilities: tuple[str, ...] = ()
    optional_capabilities: tuple[str, ...] = ()
    owns: tuple[str, ...] = ()
    validation_commands: tuple[tuple[str, ...], ...] = ()
    detection_markers: tuple[str, ...] = ()
    detection_globs: tuple[str, ...] = ()
    trust: str = "builtin-data-only"
    migrations: tuple["PackMigration", ...] = ()
    source_sha256: str = ""
    activation_conditions: tuple[str, ...] = ()
    workflows: tuple[str, ...] = ()
    schemas: tuple[str, ...] = ()
    policies: tuple[str, ...] = ()
    adapters: tuple[str, ...] = ()
    tests: tuple[str, ...] = ()


@dataclass(frozen=True)
class PackMigration:
    from_version: str
    to_version: str
    kind: str
    description: str
    argv: tuple[str, ...] = ()
    network: bool = False
    read_paths: tuple[str, ...] = ()
    write_paths: tuple[str, ...] = ()


@dataclass(frozen=True)
class Catalog:
    version: str
    roles: Mapping[str, Document]
    skills: Mapping[str, Document]
    packs: Mapping[str, Pack]
    codex_model_policy: CodexModelPolicy | None = None


@dataclass(frozen=True)
class Projection:
    """A deterministic set of relative paths and their generated contents."""

    files: Mapping[PurePosixPath, str]
    packs: tuple[str, ...]


@dataclass(frozen=True)
class Drift:
    missing: tuple[PurePosixPath, ...]
    changed: tuple[PurePosixPath, ...]
    stale: tuple[PurePosixPath, ...] = ()
    project_owned: tuple[PurePosixPath, ...] = ()

    @property
    def unexpected(self) -> tuple[PurePosixPath, ...]:
        """Compatibility alias for stale previously-managed output."""
        return self.stale

    @property
    def clean(self) -> bool:
        return not (self.missing or self.changed or self.stale)


_MARKER = "<!-- Generated by Tasktra. Edit catalog sources, then compile. -->\n"
_RUNTIME_ROOTS = (".agents", ".codex", ".claude")


def load_catalog(catalog_dir: Path | str, *, source_trust: str = "builtin") -> Catalog:
    """Load canonical role, skill, and declarative pack sources."""
    if source_trust not in {"builtin", "third-party-data-only"}:
        raise CatalogError(f"unsupported catalog source trust: {source_trust}")
    root = Path(catalog_dir)
    metadata = _read_toml(root / "catalog.toml")
    version = _require_string(metadata, "catalog", "version")
    roles = _load_documents(root / "roles", "role")
    roles.update(_load_declared_roles(root / "specialist-roles.toml", roles))
    skills = _load_skill_documents(root / "skills")
    skills.update(_load_declared_skills(root / "core-skills.toml", skills))
    packs: dict[str, Pack] = {}
    packs_root = root / "packs"
    for manifest in sorted(packs_root.glob("*/pack.toml")):
        data = _read_toml(manifest)
        try:
            validate_named(data, "pack")
        except ContractError as error:
            raise CatalogError(f"{manifest}: {error}") from error
        section = data.get("pack")
        if not isinstance(section, dict):
            raise CatalogError(f"{manifest}: missing [pack]")
        if set(data) - {"pack", "migration"}:
            raise CatalogError(f"{manifest}: unknown top-level pack fields: {', '.join(sorted(set(data) - {'pack', 'migration'}))}")
        allowed_pack_fields = {
            "id", "version", "contract_version", "trust", "dependencies", "conflicts",
            "roles", "skills", "owns", "required_capabilities", "optional_capabilities",
            "validation_commands", "detection_markers", "detection_globs",
            "activation_conditions", "workflows", "schemas", "policies", "adapters", "tests",
        }
        unknown_pack_fields = set(section) - allowed_pack_fields
        if unknown_pack_fields:
            raise CatalogError(f"{manifest}: unknown [pack] fields: {', '.join(sorted(unknown_pack_fields))}")
        identifier = _require_identifier(_require_string(data, "pack", "id"), manifest, "pack")
        if _casefold_duplicate(identifier, packs):
            raise CatalogError(f"duplicate pack id: {identifier}")
        migrations = _migrations(data.get("migration", []), manifest)
        packs[identifier] = Pack(
            identifier=identifier,
            version=_semver(_require_string(data, "pack", "version"), manifest, "pack.version"),
            dependencies=_string_list(section.get("dependencies", []), manifest),
            conflicts=_string_list(section.get("conflicts", []), manifest),
            roles=_string_list(section.get("roles", []), manifest),
            skills=_string_list(section.get("skills", []), manifest),
            contract_version=_contract_version(section.get("contract_version", 1), manifest),
            required_capabilities=_string_list(section.get("required_capabilities", []), manifest),
            optional_capabilities=_string_list(section.get("optional_capabilities", []), manifest),
            owns=_owned_list(section.get("owns", []), manifest),
            validation_commands=_argv_list(section.get("validation_commands", []), manifest),
            detection_markers=_relative_path_list(section.get("detection_markers", []), manifest),
            detection_globs=_glob_list(section.get("detection_globs", []), manifest),
            trust=(
                _trust(section.get("trust", "builtin-data-only"), manifest)
                if source_trust == "builtin"
                else "third-party-data-only"
            ),
            migrations=migrations,
            source_sha256=_pack_payload_digest(manifest, migrations),
            activation_conditions=_owned_list(section.get("activation_conditions", []), manifest),
            workflows=_string_list(section.get("workflows", []), manifest),
            schemas=_string_list(section.get("schemas", []), manifest),
            policies=_string_list(section.get("policies", []), manifest),
            adapters=_string_list(section.get("adapters", []), manifest),
            tests=_string_list(section.get("tests", []), manifest),
        )
    if "core" not in packs:
        raise CatalogError("catalog must define a core pack")
    _validate_pack_references(packs, roles, skills)
    return Catalog(version, roles, skills, packs, _codex_model_policy(metadata, root / "catalog.toml"))


def resolve_packs(catalog: Catalog, enabled_packs: Iterable[str] = ("core",)) -> tuple[str, ...]:
    """Resolve packs in dependency order; duplicate requests are ignored."""
    _validate_pack_references(catalog.packs, catalog.roles, catalog.skills)
    resolved: list[str] = []
    visiting: set[str] = set()

    def visit(identifier: str) -> None:
        if identifier in resolved:
            return
        if identifier in visiting:
            raise CatalogError(f"cyclic pack dependency at {identifier}")
        pack = catalog.packs.get(identifier)
        if pack is None:
            raise CatalogError(f"unknown pack: {identifier}")
        visiting.add(identifier)
        for dependency in sorted(pack.dependencies):
            visit(dependency)
        visiting.remove(identifier)
        for other in resolved:
            if other in pack.conflicts or identifier in catalog.packs[other].conflicts:
                raise CatalogError(f"incompatible packs: {identifier}, {other}")
        resolved.append(identifier)

    for identifier in sorted(set(enabled_packs)):
        visit(identifier)
    owners: dict[str, str] = {}
    for identifier in resolved:
        pack = catalog.packs[identifier]
        contributions = list(pack.owns)
        contribution_namespaces = {
            "workflows": "workflow",
            "schemas": "schema",
            "policies": "policy",
            "adapters": "adapter",
            "tests": "test",
        }
        for kind, namespace in contribution_namespaces.items():
            contributions.extend(f"{namespace}:{item}" for item in getattr(pack, kind))
        for owned in contributions:
            previous = owners.get(owned)
            if previous is not None and previous != identifier:
                raise CatalogError(
                    f"duplicate pack ownership for {owned!r}: {previous}, {identifier}"
                )
            owners[owned] = identifier
    return tuple(resolved)


def compile_catalog(
    catalog: Catalog,
    enabled_packs: Iterable[str] = ("core",),
    *,
    codex_model_policy: CodexModelPolicy | None = None,
    codex_role_overrides: Mapping[str, Mapping[str, str]] | None = None,
    project_routes: Iterable[ProjectRoute] = (),
    project_root: Path | str | None = None,
) -> Projection:
    """Return the exact Codex and Claude files for a selected pack set.

    Writes are intentionally separate in :func:`write_projection`, which lets
    callers preview changes before modifying a project.
    """
    packs = resolve_packs(catalog, enabled_packs)
    model_policy = codex_model_policy or catalog.codex_model_policy
    if model_policy is None:
        raise CatalogError("catalog must define a Codex model policy")
    role_overrides = codex_role_overrides or {}
    unknown_overrides = set(role_overrides) - set(catalog.roles)
    if unknown_overrides:
        raise CatalogError(
            "Codex role overrides reference unknown role(s): " + ", ".join(sorted(unknown_overrides))
        )
    role_ids = _selected(packs, catalog.packs, "roles")
    skill_ids = _selected(packs, catalog.packs, "skills")
    routes = tuple(project_routes)
    project_agents = _discover_project_agents(catalog, project_root)
    _validate_project_routes(catalog, role_ids, skill_ids, routes, project_agents, project_root)
    files: dict[PurePosixPath, str] = {
        PurePosixPath("AGENTS.md"): _entrypoint("Codex", packs, role_ids, skill_ids, routes, project_agents),
        PurePosixPath("CLAUDE.md"): _entrypoint("Claude", packs, role_ids, skill_ids, routes, project_agents),
        PurePosixPath(".tasktra", "generated", "pack-plan.json"): _pack_plan(catalog, packs),
    }
    for role_id in role_ids:
        role = catalog.roles[role_id]
        files[PurePosixPath(".agents", "roles", f"{role_id}.md")] = _MARKER + role.content
        files[PurePosixPath(".codex", "agents", f"{role_id}.toml")] = _codex_agent_projection(
            role, model_policy, role_overrides.get(role_id, {})
        )
        files[PurePosixPath(".claude", "agents", f"{role_id}.md")] = _agent_projection(role)
    for skill_id in skill_ids:
        skill = catalog.skills[skill_id]
        content = _skill_projection(skill)
        files[PurePosixPath(".agents", "skills", skill_id, "SKILL.md")] = content
        files[PurePosixPath(".claude", "skills", skill_id, "SKILL.md")] = content
    return Projection(files, packs)


def _pack_plan(catalog: Catalog, packs: tuple[str, ...]) -> str:
    contributions: dict[str, dict[str, str]] = {
        "workflows": {}, "schemas": {}, "policies": {}, "adapters": {}, "tests": {},
    }
    items: list[dict[str, object]] = []
    for identifier in packs:
        pack = catalog.packs[identifier]
        item: dict[str, object] = {
            "id": identifier,
            "version": pack.version,
            "contract_version": pack.contract_version,
            "trust": pack.trust,
            "sha256": pack.source_sha256,
            "activation_conditions": list(pack.activation_conditions),
            "required_capabilities": list(pack.required_capabilities),
            "optional_capabilities": list(pack.optional_capabilities),
            "validation_commands": [list(command) for command in pack.validation_commands],
        }
        items.append(item)
        for kind in contributions:
            for contribution in getattr(pack, kind):
                previous = contributions[kind].get(contribution)
                if previous is not None:
                    raise CatalogError(
                        f"duplicate {kind[:-1]} contribution {contribution!r}: {previous}, {identifier}"
                    )
                contributions[kind][contribution] = identifier
    value = {
        "kind": "tasktra.pack-plan",
        "version": 1,
        "packs": items,
        "contributions": {
            kind: [{"id": item, "owner": owner} for item, owner in sorted(owners.items())]
            for kind, owners in sorted(contributions.items())
        },
    }
    return json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def write_projection(project_dir: Path | str, projection: Projection) -> tuple[Path, ...]:
    """Write a projection and return written paths.

    This only writes paths in the projection.  It never deletes stale files;
    callers can present drift before choosing a cleanup policy.
    """
    project, destinations = _validate_projection_destinations(project_dir, projection.files)
    written: list[Path] = []
    staged: list[tuple[Path, Path]] = []
    try:
        for _, content, destination in destinations:
            if destination.exists() and destination.read_text(encoding="utf-8") == content:
                continue
            destination.parent.mkdir(parents=True, exist_ok=True)
            _reject_symlink_ancestors(project, destination)
            descriptor, temporary_name = tempfile.mkstemp(prefix=".tasktra-", suffix=".tmp", dir=destination.parent)
            temporary = Path(temporary_name)
            try:
                with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
                    handle.write(content)
                    handle.flush()
                    os.fsync(handle.fileno())
            except Exception:
                temporary.unlink(missing_ok=True)
                raise
            staged.append((temporary, destination))
        for temporary, destination in staged:
            os.replace(temporary, destination)
            written.append(destination)
    finally:
        for temporary, _ in staged:
            temporary.unlink(missing_ok=True)
    return tuple(written)


def check_drift(
    project_dir: Path | str,
    projection: Projection,
    *,
    managed_paths: Iterable[str | PurePosixPath] | None = None,
) -> Drift:
    """Compare an on-disk projection without changing it."""
    project, destinations = _validate_projection_destinations(project_dir, projection.files)
    expected = {relative for relative, _, _ in destinations}
    missing: list[PurePosixPath] = []
    changed: list[PurePosixPath] = []
    for relative, content, path in destinations:
        if not path.exists():
            missing.append(relative)
        elif path.read_text(encoding="utf-8") != content:
            changed.append(relative)
    actual: set[PurePosixPath] = set()
    for root_name in _RUNTIME_ROOTS:
        root = project / root_name
        if root.exists():
            actual.update(PurePosixPath(path.relative_to(project).as_posix()) for path in root.rglob("*" ) if path.is_file())
    for top_level in ("AGENTS.md", "CLAUDE.md"):
        if (project / top_level).exists():
            actual.add(PurePosixPath(top_level))
    pack_plan = project / ".tasktra" / "generated" / "pack-plan.json"
    if pack_plan.is_file():
        actual.add(PurePosixPath(".tasktra/generated/pack-plan.json"))
    if managed_paths is None:
        # Legacy callers have no ownership record, so retain conservative
        # reporting.  CLI callers pass the manifest and receive the split.
        stale = actual - expected
        project_owned: set[PurePosixPath] = set()
    else:
        managed = {_safe_projection_path(path) for path in managed_paths}
        stale = (actual & managed) - expected
        project_owned = actual - expected - stale
    return Drift(
        tuple(sorted(missing)),
        tuple(sorted(changed)),
        tuple(sorted(stale)),
        tuple(sorted(project_owned)),
    )


def catalog_digest(catalog_dir: Path | str) -> str:
    """Return a stable identity for every regular canonical source file.

    The digest intentionally includes relative names as well as bytes.  Moving
    a source is meaningful because generated-file source hints must remain
    reproducible.  Symlinked inputs are rejected rather than being followed.
    """
    root = Path(catalog_dir).resolve()
    if not root.is_dir():
        raise CatalogError(f"catalog directory does not exist: {root}")
    digest = sha256()
    for source in sorted(root.rglob("*")):
        if source.is_symlink():
            raise CatalogError(f"catalog source cannot be a symlink: {source}")
        if not source.is_file():
            continue
        relative = source.relative_to(root).as_posix().encode("utf-8")
        raw = source.read_bytes()
        digest.update(len(relative).to_bytes(4, "big"))
        digest.update(relative)
        digest.update(len(raw).to_bytes(8, "big"))
        digest.update(raw)
    return digest.hexdigest()


def _safe_projection_path(value: str | PurePosixPath) -> PurePosixPath:
    raw = str(value)
    if not raw or "\\" in raw or ":" in raw:
        raise ProjectionError(f"generated path must use a safe relative POSIX path: {value}")
    path = PurePosixPath(raw)
    if path.is_absolute() or ".." in path.parts or str(path) in {"", "."} or path.as_posix() != raw:
        raise ProjectionError(f"generated path must use a safe relative POSIX path: {value}")
    return path


def _validate_projection_destinations(
    project_dir: Path | str, files: Mapping[PurePosixPath, str]
) -> tuple[Path, tuple[tuple[PurePosixPath, str, Path], ...]]:
    project = Path(project_dir).resolve()
    if project.exists() and not project.is_dir():
        raise ProjectionError(f"project directory is not a directory: {project}")
    normalized: set[PurePosixPath] = set()
    destinations: list[tuple[PurePosixPath, str, Path]] = []
    for relative, content in files.items():
        safe_relative = _safe_projection_path(relative)
        if safe_relative in normalized:
            raise ProjectionError(f"duplicate generated path: {safe_relative}")
        if not isinstance(content, str):
            raise ProjectionError(f"generated content for {safe_relative} must be text")
        destination = project.joinpath(*safe_relative.parts)
        _reject_symlink_ancestors(project, destination)
        try:
            destination.resolve(strict=False).relative_to(project)
        except ValueError as error:
            raise ProjectionError(f"generated path escapes project directory: {safe_relative}") from error
        normalized.add(safe_relative)
        destinations.append((safe_relative, content, destination))
    return project, tuple(destinations)


def _reject_symlink_ancestors(project: Path, destination: Path) -> None:
    """Reject any redirecting filesystem object, including Windows junctions."""
    relative = destination.relative_to(project)
    cursor = project
    for part in relative.parts:
        cursor = cursor / part
        if _is_linklike(cursor):
            raise ProjectionError(f"generated path crosses a link or reparse point: {relative.as_posix()}")


def _require_identifier(value: object, source: Path, kind: str) -> str:
    try:
        return require_identifier(value, label=f"{kind} id")
    except IdentifierError as error:
        raise CatalogError(
            f"{source}: {kind} id must use a lowercase slug of at most 64 characters"
        ) from error


def _casefold_duplicate(identifier: str, definitions: Mapping[str, object]) -> bool:
    return any(identifier.casefold() == existing.casefold() for existing in definitions)


def _load_documents(directory: Path, kind: str) -> dict[str, Document]:
    documents: dict[str, Document] = {}
    for source in sorted(directory.glob("*.md")):
        frontmatter, content = _frontmatter(source)
        identifier = frontmatter.get("id")
        title = frontmatter.get("title")
        family = frontmatter.get("family")
        if not all(isinstance(value, str) and value for value in (identifier, title, family)):
            raise CatalogError(f"{source}: {kind} requires id, title, and family frontmatter")
        identifier = _require_identifier(identifier, source, kind)
        if _casefold_duplicate(identifier, documents):
            raise CatalogError(f"duplicate {kind} id: {identifier}")
        metadata = _role_metadata(frontmatter, source) if kind == "role" else None
        if kind == "role":
            unknown = set(frontmatter) - {"id", "title", "family", "model_tier", "reasoning_effort", "sandbox_mode"}
            if unknown:
                raise CatalogError(f"{source}: unknown role frontmatter fields: {', '.join(sorted(unknown))}")
        documents[identifier] = Document(
            identifier, title, family, source, content,
            metadata.model_tier if metadata else None,
            metadata.reasoning_effort if metadata else None,
            metadata.sandbox_mode if metadata else None,
        )
    if not documents:
        raise CatalogError(f"no {kind} documents in {directory}")
    return documents


def _load_skill_documents(directory: Path) -> dict[str, Document]:
    return _load_documents(directory, "skill")


def _load_declared_roles(source: Path, existing: Mapping[str, Document]) -> dict[str, Document]:
    """Expand concise specialist declarations into role documents.

    Specialists share the core bounded-work contract; declarations therefore
    carry only the expertise that differs, avoiding copied policy prose.
    """
    data = _read_toml(source)
    entries = data.get("role")
    if not isinstance(entries, list):
        raise CatalogError(f"{source}: expected [[role]] declarations")
    documents: dict[str, Document] = {}
    for entry in entries:
        if not isinstance(entry, dict):
            raise CatalogError(f"{source}: role declarations must be tables")
        unknown = set(entry) - {
            "id", "title", "family", "focus", "trigger", "responsibility", "evidence_policy",
            "inputs", "outputs", "stop_conditions", "validation_expectations",
            "model_tier", "reasoning_effort", "sandbox_mode",
        }
        if unknown:
            raise CatalogError(f"{source}: unknown role fields: {', '.join(sorted(unknown))}")
        identifier = entry.get("id")
        title = entry.get("title")
        family = entry.get("family")
        focus = entry.get("focus")
        trigger = entry.get("trigger")
        responsibility = entry.get("responsibility")
        evidence_policy = entry.get("evidence_policy")
        scalar_fields = (identifier, title, family, focus, trigger, responsibility, evidence_policy)
        if not all(isinstance(value, str) and value for value in scalar_fields):
            raise CatalogError(
                f"{source}: role requires id, title, family, focus, trigger, responsibility, and evidence_policy"
            )
        inputs = _role_contract_list(entry.get("inputs"), source, identifier, "inputs")
        outputs = _role_contract_list(entry.get("outputs"), source, identifier, "outputs")
        stops = _role_contract_list(entry.get("stop_conditions"), source, identifier, "stop_conditions")
        validations = _role_contract_list(
            entry.get("validation_expectations"), source, identifier, "validation_expectations"
        )
        identifier = _require_identifier(identifier, source, "role")
        if _casefold_duplicate(identifier, existing) or _casefold_duplicate(identifier, documents):
            raise CatalogError(f"duplicate role id: {identifier}")
        content = (
            f"# {title}\n\n{focus}\n\n"
            f"## Trigger\n\n{trigger}\n\n"
            f"## Owned responsibility\n\n{responsibility}\n\n"
            f"## Inputs\n\n{_bullets(inputs)}\n\n"
            f"## Outputs\n\n{_bullets(outputs)}\n\n"
            f"## Stop conditions\n\n{_bullets(stops)}\n\n"
            f"## Validation expectations\n\n{_bullets(validations)}\n\n"
            f"## Evidence policy\n\n{evidence_policy}\n"
        )
        metadata = _role_metadata(entry, source)
        documents[identifier] = Document(
            identifier, title, family, source, content,
            metadata.model_tier, metadata.reasoning_effort, metadata.sandbox_mode,
        )
    return documents


def _role_contract_list(value: object, source: Path, identifier: object, label: str) -> tuple[str, ...]:
    if not isinstance(value, list) or not value or not all(isinstance(item, str) and item for item in value):
        raise CatalogError(f"{source}: role {identifier!r} {label} must be a non-empty string list")
    return tuple(value)


def _codex_model_policy(data: Mapping[str, object], source: Path) -> CodexModelPolicy:
    section = data.get("codex")
    if not isinstance(section, dict) or set(section) != {"model_tiers"}:
        raise CatalogError(f"{source}: [codex] must contain only model_tiers")
    tiers = section["model_tiers"]
    if not isinstance(tiers, dict):
        raise CatalogError(f"{source}: codex.model_tiers must be a table")
    try:
        return CodexModelPolicy(tiers)
    except ModelPolicyError as error:
        raise CatalogError(f"{source}: {error}") from error


def _role_metadata(data: Mapping[str, object], source: Path) -> RoleModelMetadata:
    """Require closed portable execution metadata on every canonical role."""
    try:
        return RoleModelMetadata(
            model_tier=data.get("model_tier"),  # type: ignore[arg-type]
            reasoning_effort=data.get("reasoning_effort"),  # type: ignore[arg-type]
            sandbox_mode=data.get("sandbox_mode"),  # type: ignore[arg-type]
        )
    except ModelPolicyError as error:
        raise CatalogError(f"{source}: {error}") from error


def _bullets(values: tuple[str, ...]) -> str:
    return "\n".join(f"- {value}" for value in values)


def _load_declared_skills(source: Path, existing: Mapping[str, Document]) -> dict[str, Document]:
    """Expand compact core skill declarations into canonical documents."""
    data = _read_toml(source)
    entries = data.get("skill")
    if not isinstance(entries, list):
        raise CatalogError(f"{source}: expected [[skill]] declarations")
    documents: dict[str, Document] = {}
    for entry in entries:
        if not isinstance(entry, dict):
            raise CatalogError(f"{source}: skill declarations must be tables")
        identifier = entry.get("id")
        title = entry.get("title")
        purpose = entry.get("purpose")
        if not all(isinstance(value, str) and value for value in (identifier, title, purpose)):
            raise CatalogError(f"{source}: skill requires id, title, and purpose")
        identifier = _require_identifier(identifier, source, "skill")
        if _casefold_duplicate(identifier, existing) or _casefold_duplicate(identifier, documents):
            raise CatalogError(f"duplicate skill id: {identifier}")
        content = f"# {title}\n\n{purpose}\n"
        documents[identifier] = Document(identifier, title, "core", source, content)
    return documents


def _frontmatter(source: Path) -> tuple[dict[str, str], str]:
    raw = source.read_text(encoding="utf-8")
    if not raw.startswith("---\n"):
        raise CatalogError(f"{source}: expected TOML frontmatter")
    closing = raw.find("\n---\n", 4)
    if closing == -1:
        raise CatalogError(f"{source}: unclosed frontmatter")
    frontmatter = tomllib.loads(raw[4:closing])
    return frontmatter, raw[closing + 5 :]


def _read_toml(path: Path) -> dict:
    try:
        return tomllib.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise CatalogError(f"missing catalog file: {path}") from exc
    except tomllib.TOMLDecodeError as exc:
        raise CatalogError(f"invalid TOML: {path}: {exc}") from exc


def _require_string(data: dict, section_name: str, key: str) -> str:
    section = data.get(section_name)
    value = section.get(key) if isinstance(section, dict) else None
    if not isinstance(value, str) or not value:
        raise CatalogError(f"[{section_name}] requires {key}")
    return value


def _string_list(value: object, source: Path) -> tuple[str, ...]:
    if not isinstance(value, list) or not all(isinstance(item, str) and item for item in value):
        raise CatalogError(f"{source}: expected a list of non-empty strings")
    result = tuple(_require_identifier(item, source, "pack reference") for item in value)
    if len(set(result)) != len(result):
        raise CatalogError(f"{source}: list must not contain duplicate references")
    return result


def _positive_int(value: object, source: Path, label: str) -> int:
    if not isinstance(value, int) or isinstance(value, bool) or value < 1:
        raise CatalogError(f"{source}: {label} must be a positive integer")
    return value


def _contract_version(value: object, source: Path) -> int:
    version = _positive_int(value, source, "contract_version")
    if version != 1:
        raise CatalogError(f"{source}: unsupported pack contract_version: {version}")
    return version


def _owned_list(value: object, source: Path) -> tuple[str, ...]:
    if not isinstance(value, list) or not all(isinstance(item, str) and item for item in value):
        raise CatalogError(f"{source}: owns must be a list of non-empty strings")
    if len(set(value)) != len(value):
        raise CatalogError(f"{source}: owns must not contain duplicates")
    return tuple(value)


def _argv_list(value: object, source: Path) -> tuple[tuple[str, ...], ...]:
    if not isinstance(value, list):
        raise CatalogError(f"{source}: validation_commands must be a list of argv arrays")
    commands: list[tuple[str, ...]] = []
    for index, command in enumerate(value):
        if not isinstance(command, list) or not command or not all(isinstance(item, str) and item for item in command):
            raise CatalogError(f"{source}: validation_commands[{index}] must be a non-empty argv array")
        if any("\x00" in item for item in command):
            raise CatalogError(f"{source}: validation command contains NUL")
        commands.append(tuple(command))
    if len(set(commands)) != len(commands):
        raise CatalogError(f"{source}: validation_commands must not contain duplicates")
    return tuple(commands)


def _relative_path_list(value: object, source: Path) -> tuple[str, ...]:
    if not isinstance(value, list) or not all(isinstance(item, str) and item for item in value):
        raise CatalogError(f"{source}: detection_markers must be a list of relative paths")
    result: list[str] = []
    for item in value:
        path = PurePosixPath(item)
        if path.is_absolute() or path.as_posix() == "." or ".." in path.parts or "\\" in item or ":" in item or path.as_posix() != item:
            raise CatalogError(f"{source}: unsafe detection marker: {item}")
        result.append(item)
    if len(set(result)) != len(result):
        raise CatalogError(f"{source}: detection_markers must not contain duplicates")
    return tuple(result)


def _glob_list(value: object, source: Path) -> tuple[str, ...]:
    if not isinstance(value, list) or not all(isinstance(item, str) and item for item in value):
        raise CatalogError(f"{source}: detection_globs must be a list of bounded patterns")
    for item in value:
        if "**" in item or ".." in PurePosixPath(item).parts or "\\" in item or ":" in item:
            raise CatalogError(f"{source}: detection glob must be bounded and relative: {item}")
    if len(set(value)) != len(value):
        raise CatalogError(f"{source}: detection_globs must not contain duplicates")
    return tuple(value)


def _trust(value: object, source: Path) -> str:
    allowed = {"builtin-data-only", "third-party-data-only", "third-party-executable"}
    if not isinstance(value, str) or value not in allowed:
        raise CatalogError(f"{source}: trust must be one of {', '.join(sorted(allowed))}")
    return value


def _semver(value: object, source: Path, label: str) -> str:
    if not isinstance(value, str):
        raise CatalogError(f"{source}: {label} must be a semantic version")
    parts = value.split(".")
    if len(parts) != 3 or any(not part.isdigit() for part in parts):
        raise CatalogError(f"{source}: {label} must be a semantic version")
    return value


def _migrations(value: object, source: Path) -> tuple[PackMigration, ...]:
    if not isinstance(value, list):
        raise CatalogError(f"{source}: [[migration]] must be an array of tables")
    migrations: list[PackMigration] = []
    edges: set[tuple[str, str]] = set()
    for item in value:
        allowed = {"from", "to", "kind", "description", "argv", "network", "read_paths", "write_paths"}
        if not isinstance(item, dict) or not {"from", "to", "kind", "description"}.issubset(item) or set(item) - allowed:
            raise CatalogError(f"{source}: migration declaration has missing or unknown fields")
        before = _semver(item["from"], source, "migration.from")
        after = _semver(item["to"], source, "migration.to")
        kind, description = item["kind"], item["description"]
        if kind not in {"declarative", "executable"}:
            raise CatalogError(f"{source}: migration.kind must be declarative or executable")
        if not isinstance(description, str) or not description.strip():
            raise CatalogError(f"{source}: migration.description must be non-empty")
        if (before, after) in edges or before == after:
            raise CatalogError(f"{source}: duplicate or no-op migration {before} -> {after}")
        edges.add((before, after))
        argv_raw = item.get("argv", [])
        network = item.get("network", False)
        read_paths = _relative_path_list(item.get("read_paths", []), source)
        write_paths = _relative_path_list(item.get("write_paths", []), source)
        if not isinstance(argv_raw, list) or not all(isinstance(value, str) and value for value in argv_raw):
            raise CatalogError(f"{source}: migration.argv must be an argv array")
        if not isinstance(network, bool):
            raise CatalogError(f"{source}: migration.network must be boolean")
        if kind == "executable" and (not argv_raw or not read_paths):
            raise CatalogError(f"{source}: executable migration requires argv and bounded read_paths")
        if kind == "executable" and not (set(argv_raw) & set(read_paths)):
            raise CatalogError(f"{source}: executable migration argv must name a hashed read_path payload")
        if kind == "executable":
            root = source.parent.resolve()
            local_argv_payloads: set[str] = set()
            for index, argument in enumerate(argv_raw):
                argument_path = Path(argument)
                bare_tool = (
                    index == 0
                    and argument not in {".", ".."}
                    and "/" not in argument
                    and "\\" not in argument
                    and not argument_path.is_absolute()
                    and not argument_path.drive
                    and not argument_path.root
                )
                if bare_tool and os.name == "nt":
                    for suffix in (".com", ".exe", ".bat", ".cmd"):
                        shadow = source.parent / f"{argument}{suffix}"
                        if shadow.exists() or _is_linklike(shadow):
                            raise CatalogError(
                                f"{source}: executable migration bare argv[0] is shadowed by pack content: {shadow.name}"
                            )
                candidate = argument_path if argument_path.is_absolute() else source.parent.joinpath(*PurePosixPath(argument).parts)
                if bare_tool and _is_linklike(candidate):
                    raise CatalogError(
                        f"{source}: executable migration bare argv[0] is a pack-local link or reparse point: {argument}"
                    )
                try:
                    resolved = candidate.resolve(strict=True)
                except (FileNotFoundError, OSError) as error:
                    if index == 0 and not bare_tool:
                        raise CatalogError(
                            f"{source}: executable migration argv[0] path is missing or unhashable: {argument}"
                        ) from error
                    continue
                try:
                    resolved.relative_to(root)
                except ValueError as error:
                    # A bare argv[0] is resolved by the trusted host PATH and is
                    # already bound by the manifest hash. Explicit filesystem
                    # payloads outside the pack cannot be checksum-bound here.
                    if resolved.exists() and not bare_tool:
                        raise CatalogError(
                            f"{source}: executable migration argv names an external unhashable path: {argument}"
                        ) from error
                    continue
                if resolved.is_dir():
                    raise CatalogError(
                        f"{source}: executable migration argv directory payloads are unsupported: {argument}"
                    )
                if resolved.is_file():
                    local_argv_payloads.add(PurePosixPath(argument).as_posix())
            unhashed = sorted(local_argv_payloads - set(read_paths))
            if unhashed:
                raise CatalogError(
                    f"{source}: executable migration argv names unhashed local payloads: {', '.join(unhashed)}"
                )
        if kind == "declarative" and (argv_raw or network or read_paths or write_paths):
            raise CatalogError(f"{source}: declarative migration cannot declare executable effects")
        migrations.append(PackMigration(before, after, kind, description, tuple(argv_raw), network, read_paths, write_paths))
    return tuple(migrations)


def _pack_payload_digest(manifest: Path, migrations: tuple[PackMigration, ...]) -> str:
    digest = sha256()
    total = 0
    sources = {manifest.resolve()}
    root = manifest.parent.resolve()
    for migration in migrations:
        if migration.kind != "executable":
            continue
        for relative in migration.read_paths:
            candidate = root.joinpath(*PurePosixPath(relative).parts)
            cursor = root
            for part in PurePosixPath(relative).parts:
                cursor = cursor / part
                if _is_linklike(cursor):
                    raise CatalogError(f"{manifest}: executable migration payload crosses a symlink: {relative}")
            try:
                resolved = candidate.resolve(strict=True)
                resolved.relative_to(root)
            except (FileNotFoundError, ValueError) as error:
                raise CatalogError(f"{manifest}: executable migration payload is missing or escapes its pack: {relative}") from error
            if not resolved.is_file():
                raise CatalogError(f"{manifest}: executable migration read_path must be a file: {relative}")
            sources.add(resolved)
    for source in sorted(sources, key=lambda path: path.as_posix()):
        raw = source.read_bytes()
        total += len(raw)
        if total > 1024 * 1024:
            raise CatalogError(f"{manifest}: executable pack payload exceeds 1 MiB")
        relative = source.relative_to(root).as_posix().encode("utf-8")
        digest.update(len(relative).to_bytes(4, "big"))
        digest.update(relative)
        digest.update(len(raw).to_bytes(8, "big"))
        digest.update(raw)
    return digest.hexdigest()


def _is_linklike(path: Path) -> bool:
    is_junction = getattr(path, "is_junction", None)
    if path.is_symlink() or bool(is_junction and is_junction()):
        return True
    try:
        attributes = os.stat(path, follow_symlinks=False).st_file_attributes
    except (AttributeError, OSError):
        return False
    return bool(attributes & stat.FILE_ATTRIBUTE_REPARSE_POINT)


def _validate_pack_references(packs: Mapping[str, Pack], roles: Mapping[str, Document], skills: Mapping[str, Document]) -> None:
    for pack in packs.values():
        if pack.contract_version != 1:
            raise CatalogError(f"{pack.identifier}: unsupported pack contract_version: {pack.contract_version}")
        if pack.trust != "builtin-data-only" and (pack.roles or pack.skills):
            raise CatalogError(
                f"{pack.identifier}: non-builtin pack content cannot become agent roles or skills"
            )
        overlap = set(pack.required_capabilities) & set(pack.optional_capabilities)
        if overlap:
            raise CatalogError(f"{pack.identifier}: capabilities cannot be both required and optional: {', '.join(sorted(overlap))}")
        unknown = set(pack.dependencies) - set(packs)
        if unknown:
            raise CatalogError(f"{pack.identifier}: unknown dependencies: {', '.join(sorted(unknown))}")
        unknown = set(pack.conflicts) - set(packs)
        if unknown:
            raise CatalogError(f"{pack.identifier}: unknown conflicts: {', '.join(sorted(unknown))}")
        if pack.identifier in pack.conflicts:
            raise CatalogError(f"{pack.identifier}: pack cannot conflict with itself")
        unknown = set(pack.roles) - set(roles)
        if unknown:
            raise CatalogError(f"{pack.identifier}: unknown roles: {', '.join(sorted(unknown))}")
        unknown = set(pack.skills) - set(skills)
        if unknown:
            raise CatalogError(f"{pack.identifier}: unknown skills: {', '.join(sorted(unknown))}")


def _selected(packs: Iterable[str], definitions: Mapping[str, Pack], attribute: str) -> tuple[str, ...]:
    selected: list[str] = []
    for identifier in packs:
        for item in getattr(definitions[identifier], attribute):
            if item not in selected:
                selected.append(item)
    return tuple(selected)


def _discover_project_agents(
    catalog: Catalog, project_root: Path | str | None
) -> tuple[ProjectAgent, ...]:
    """Treat project-owned Codex agent files as opted-in selection defaults."""
    if project_root is None:
        return ()
    project = Path(project_root).resolve()
    directory = project / ".codex" / "agents"
    _reject_symlink_ancestors(project, directory)
    if not directory.exists():
        return ()
    if not directory.is_dir():
        raise CatalogError(f"project agent path is not a directory: {directory}")
    sources = sorted(
        source for source in directory.glob("*.toml")
        if source.stem not in catalog.roles
    )
    if len(sources) > 64:
        raise CatalogError(f"project has more than 64 project-owned Codex agent files: {directory}")
    discovered: list[ProjectAgent] = []
    for source in sources:
        identifier = source.stem
        try:
            require_identifier(identifier, label="project agent")
        except IdentifierError as error:
            raise CatalogError(f"{source}: {error}") from error
        _reject_symlink_ancestors(project, source)
        try:
            if source.stat().st_size > 64 * 1024:
                raise CatalogError(f"project agent file exceeds 64 KiB: {source}")
            agent = tomllib.loads(source.read_text(encoding="utf-8"))
        except (OSError, UnicodeError, tomllib.TOMLDecodeError) as error:
            raise CatalogError(f"project agent file is unreadable or invalid: {source}") from error
        if agent.get("name") != identifier:
            raise CatalogError(f"project agent file must declare name = {identifier!r}: {source}")
        description = agent.get("description")
        if not isinstance(description, str) or not description.strip():
            raise CatalogError(f"project agent needs a description for default routing: {source}")
        summary = " ".join(description.split())
        if not summary.isprintable():
            raise CatalogError(f"project agent description must be printable: {source}")
        if len(summary) > 240:
            summary = summary[:237].rstrip() + "..."
        discovered.append(ProjectAgent(identifier, summary))
    return tuple(discovered)


def _validate_project_routes(
    catalog: Catalog,
    roles: tuple[str, ...],
    skills: tuple[str, ...],
    routes: tuple[ProjectRoute, ...],
    project_agents: tuple[ProjectAgent, ...],
    project_root: Path | str | None,
) -> None:
    project_role_ids = {agent.identifier for agent in project_agents}
    identifiers: set[str] = set()
    triggers: set[str] = set()
    for route in routes:
        try:
            require_identifier(route.identifier, label="route id")
        except IdentifierError as error:
            raise CatalogError(str(error)) from error
        trigger = route.trigger.strip()
        if not trigger or len(trigger) > 240 or not trigger.isprintable():
            raise CatalogError(f"route {route.identifier}: trigger must be one printable line of at most 240 characters")
        if route.boundary is not None and (
            not route.boundary.strip() or len(route.boundary) > 400 or not route.boundary.isprintable()
        ):
            raise CatalogError(f"route {route.identifier}: boundary must be one printable line of at most 400 characters")
        if route.role is not None and route.roles:
            raise CatalogError(f"route {route.identifier}: role and roles cannot both be set")
        if route.role is None and not route.roles and not route.skills:
            raise CatalogError(f"route {route.identifier}: a role or skill is required")
        if len({role.casefold() for role in route.roles}) != len(route.roles):
            raise CatalogError(f"route {route.identifier}: duplicate roles")
        if route.identifier.casefold() in identifiers or trigger.casefold() in triggers:
            raise CatalogError(f"route {route.identifier}: duplicate route id or trigger")
        identifiers.add(route.identifier.casefold())
        triggers.add(trigger.casefold())
        for role in ((route.role,) if route.role is not None else route.roles):
            try:
                require_identifier(role, label="route role")
            except IdentifierError as error:
                raise CatalogError(str(error)) from error
            if role in catalog.roles:
                if role not in roles:
                    raise CatalogError(f"route {route.identifier}: role {role} requires an enabled pack")
            else:
                if _casefold_duplicate(role, catalog.roles):
                    raise CatalogError(f"route {route.identifier}: role {role} conflicts with a catalog role")
                if project_root is None:
                    raise CatalogError(f"route {route.identifier}: project root is required for custom role {role}")
                if role not in project_role_ids:
                    source = Path(project_root).resolve() / ".codex" / "agents" / f"{role}.toml"
                    raise CatalogError(f"route {route.identifier}: custom role file is missing: {source}")
        for skill in route.skills:
            if not re.fullmatch(r"[a-z0-9][a-z0-9._:-]*", skill):
                raise CatalogError(f"route {route.identifier}: invalid skill name: {skill}")
            if skill in catalog.skills and skill not in skills:
                raise CatalogError(f"route {route.identifier}: skill {skill} requires an enabled pack")
            if skill not in catalog.skills and _casefold_duplicate(skill, catalog.skills):
                raise CatalogError(f"route {route.identifier}: skill {skill} conflicts with a catalog skill")


def _route_entrypoint(routes: tuple[ProjectRoute, ...]) -> str:
    if not routes:
        return ""
    lines = [
        "\nProject routes from `.tasktra/project.toml` (selection guidance, not runtime enforcement):",
        "Match substantive requests below. Skills supply procedures; selecting a skill does not dispatch a specialist. "
        "Apply each skill's own trigger, including explicit-only triggers. Check skill and tool availability in the "
        "active session; external skill names are host-unverified. Routes grant no new effect authority.",
        "When a route names several specialists, choose bounded subtasks and dispatch only where the host and current work allow it.",
    ]
    for route in routes:
        targets: list[str] = []
        if route.role:
            targets.append(f"specialist `{route.role}`")
        elif route.roles:
            targets.append("specialists " + ", ".join(f"`{role}`" for role in route.roles) + " as needed")
        if route.skills:
            targets.append("skill " + ", ".join(f"`{skill}`" for skill in route.skills) + " when applicable")
        line = f"- {route.trigger} → {'; '.join(targets)}."
        if route.boundary:
            line += f" {route.boundary}"
        lines.append(line)
    return "\n".join(lines) + "\n"


def _project_agent_entrypoint(agents: tuple[ProjectAgent, ...]) -> str:
    if not agents:
        return ""
    lines = [
        "\nProject-owned Codex specialists are opted in by their `.codex/agents/*.toml` files. "
        "Use the matching specialist for substantive bounded work even when the user does not name it. "
        "Read its agent file and preserve its model and effort pins. Other hosts must verify an equivalent agent before dispatch:",
    ]
    lines.extend(
        f"- `{agent.identifier}` (`.codex/agents/{agent.identifier}.toml`): {agent.description}"
        for agent in agents
    )
    return "\n".join(lines) + "\n"


def _entrypoint(
    runtime: str, packs: tuple[str, ...], roles: tuple[str, ...], skills: tuple[str, ...],
    routes: tuple[ProjectRoute, ...] = (), project_agents: tuple[ProjectAgent, ...] = (),
) -> str:
    return (
        _MARKER
        +
        f"# Tasktra {runtime} entrypoint\n\n"
        "Use the assigned role for bounded work. Read a skill only when its trigger applies. "
        "Project authority, goal scope, and validation live in `.tasktra/project.toml` and project-owned policy sources.\n\n"
        "Apply the efficiency ladder: reuse verified evidence; use deterministic tools for mechanical work; "
        "delegate narrow retrieval to a scout; delegate concrete changes to a bounded implementer; use reviewers "
        "for independent semantic judgment; and escalate only a specific unresolved difficulty. Do not delegate "
        "a deterministic status, search, count, formatting, or comparison merely to avoid using a tool. Never "
        "skip required validation to save model usage.\n\n"
        "Enabled pack roles and project-owned `.codex/agents/*.toml` agents are opted-in defaults: select a matching "
        "specialist by its description for substantive bounded work when the host permits delegation. Follow explicit "
        "user model and no-subagent "
        "choices and runtime delegation limits. Check host availability; if unavailable, state the limitation, use a "
        "suitable role or follow the workflow locally, and report what actually ran.\n\n"
        f"Enabled packs: {', '.join(packs)}\n\n"
        f"Roles: {', '.join(roles)}\n\n"
        f"Skills: {', '.join(skills)}\n"
        + _project_agent_entrypoint(project_agents)
        + _route_entrypoint(routes)
    )


def _agent_projection(role: Document) -> str:
    """Render Codex/Claude agent metadata from a neutral document."""
    return _yaml_header(role.identifier, _summary(role)) + _MARKER + role.content


def _codex_agent_projection(
    role: Document, model_policy: CodexModelPolicy, override: Mapping[str, str]
) -> str:
    """Render a native Codex custom-agent TOML definition."""
    try:
        metadata = RoleModelMetadata(role.model_tier, role.reasoning_effort, role.sandbox_mode)
        model = model_policy.model_for(metadata.model_tier)
    except ModelPolicyError as error:
        raise CatalogError(f"{role.source}: invalid Codex role metadata: {error}") from error
    if set(override) - {"model", "reasoning_effort"}:
        raise CatalogError(f"{role.source}: invalid Codex role override")
    model = None if override.get("model") == "inherit" else override.get("model", model)
    effort = None if override.get("reasoning_effort") == "inherit" else override.get("reasoning_effort", metadata.reasoning_effort)
    if model is not None and (not isinstance(model, str) or not model.strip()):
        raise CatalogError(f"{role.source}: invalid Codex model override")
    if effort is not None:
        try:
            RoleModelMetadata(metadata.model_tier, effort, metadata.sandbox_mode)
        except ModelPolicyError as error:
            raise CatalogError(f"{role.source}: invalid Codex reasoning override: {error}") from error
    return (
        "# Generated by Tasktra. Edit catalog sources, then compile.\n"
        f"name = {json.dumps(role.identifier)}\n"
        f"description = {json.dumps(_summary(role))}\n"
        + (f"model = {json.dumps(model)}\n" if model is not None else "")
        + (f"model_reasoning_effort = {json.dumps(effort)}\n" if effort is not None else "")
        + f"sandbox_mode = {json.dumps(metadata.sandbox_mode)}\n"
        + f"developer_instructions = {json.dumps(role.content)}\n"
    )


def _skill_projection(skill: Document) -> str:
    """Render a runtime-valid SKILL.md with discoverable YAML frontmatter."""
    return _yaml_header(skill.identifier, _summary(skill)) + _MARKER + skill.content


def _summary(document: Document) -> str:
    lines = (line.strip() for line in document.content.splitlines())
    for line in lines:
        if line and not line.startswith("#"):
            return line
    return document.title


def _yaml_header(name: str, description: str) -> str:
    escaped = description.replace("\\", "\\\\").replace('"', '\\"')
    return f"---\nname: {name}\ndescription: \"{escaped}\"\n---\n"
